// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → Company Values*
 */
export interface AboutDocumentDataValuesItem {
  /**
   * Value Title field in *About → Company Values*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.values[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Value Description field in *About → Company Values*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.values[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: About page content
   * - **API ID Path**: about.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Company Values field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.values[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  values: prismic.GroupField<Simplify<AboutDocumentDataValuesItem>>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type ClientsDocumentDataSlicesSlice = never;

/**
 * Content for Clients documents
 */
interface ClientsDocumentData {
  /**
   * title field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: clients.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Description ( Must )
   * - **API ID Path**: clients.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Clients*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientsDocumentDataSlicesSlice> /**
   * Meta Title field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clients.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clients.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Clients document from Prismic
 *
 * - **API ID**: `clients`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientsDocumentData>,
    "clients",
    Lang
  >;

type ClientsPostDocumentDataSlicesSlice = never;

/**
 * Content for Client Post documents
 */
interface ClientsPostDocumentData {
  /**
   * title field in *Client Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: clients_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Client Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Description ( Must )
   * - **API ID Path**: clients_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Client Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * year field in *Client Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Enter Signed Year ( Must )
   * - **API ID Path**: clients_post.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  year: prismic.DateField;

  /**
   * type field in *Client Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Enter Type ( Must )
   * - **Default Value**: actor
   * - **API ID Path**: clients_post.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"actor" | "serie" | "production", "filled">;

  /**
   * Slice Zone field in *Client Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientsPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Client Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clients_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Client Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clients_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Client Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Client Post document from Prismic
 *
 * - **API ID**: `clients_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientsPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClientsPostDocumentData>,
    "clients_post",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | CtaSlice
  | WhyChooseUsSlice
  | TeamSlice
  | MiniServicesSlice
  | HeroSectionSlice
  | BriefSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Product Post → Product Gallery*
 */
export interface ProductPostDocumentDataGalleryImagesItem {
  /**
   * Gallery Image field in *Product Post → Product Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption field in *Product Post → Product Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter image caption
   * - **API ID Path**: product_post.gallery_images[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Item in *Product Post → Specification Groups → Specifications*
 */
export interface ProductPostDocumentDataSpecificationGroupsSpecificationsItem {
  /**
   * Specification Name field in *Product Post → Specification Groups → Specifications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Size, Weight, Material
   * - **API ID Path**: product_post.specification_groups[].specifications[].spec_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spec_name: prismic.KeyTextField;

  /**
   * Specification Value field in *Product Post → Specification Groups → Specifications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., 10mm, 500g, Stainless Steel
   * - **API ID Path**: product_post.specification_groups[].specifications[].spec_value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spec_value: prismic.KeyTextField;
}

/**
 * Item in *Product Post → Specification Groups*
 */
export interface ProductPostDocumentDataSpecificationGroupsItem {
  /**
   * Group Title field in *Product Post → Specification Groups*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Physical Properties, Technical Details
   * - **API ID Path**: product_post.specification_groups[].group_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_title: prismic.KeyTextField;

  /**
   * Specifications field in *Product Post → Specification Groups*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.specification_groups[].specifications[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  specifications: prismic.NestedGroupField<
    Simplify<ProductPostDocumentDataSpecificationGroupsSpecificationsItem>
  >;
}

type ProductPostDocumentDataSlicesSlice = never;

/**
 * Content for Product Post documents
 */
interface ProductPostDocumentData {
  /**
   * Product Title field in *Product Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter product title
   * - **API ID Path**: product_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Product Subtitle field in *Product Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter product subtitle
   * - **API ID Path**: product_post.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Category field in *Product Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select product category
   * - **API ID Path**: product_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Irrigation"
    | "Waterworks"
    | "Fire Protection"
    | "Filtration"
    | "Mechanical Valves"
  >;

  /**
   * Subcategory field in *Product Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select product subcategory
   * - **API ID Path**: product_post.subcategory
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  subcategory: prismic.SelectField<
    | "On/Off - Solenoid"
    | "Pressure Reducing"
    | "Pressure Relief/Sustaining"
    | "Level Control"
    | "Flow Control"
    | "Filter Back-Flushing"
    | "Pump Stations"
    | "Air Valves"
    | "Surge Control"
    | "Flow Rate Control"
    | "Pump Control"
    | "Check Valves"
    | "Solenoid Controlled"
    | "Sprinkler"
    | "Alarm Check Valves"
    | "Dry Alarm Valve"
    | "Butterfly Valves"
    | "Waterflow Detector"
    | "Test & Drain Valve"
    | "OS&Y Gate Valves"
    | "Pressure Reducing/Relief"
    | "Pre-Action Valve"
    | "Deluge Valves"
    | "Monitor Valves"
    | "Fire Hydrants"
    | "Auto Screen Filters"
    | "Auto Disc Filters"
    | "Manual Plastic Filters"
    | "Gravel (Media) Filters"
    | "Hydrocyclones"
    | "Suction Filters"
    | "Metal Filters"
    | "Fertilizer Tanks"
    | "Ball Valves"
    | "Gate Valves"
    | "Float Valves"
    | "Strainers"
    | "Dismantling Joints"
  >;

  /**
   * Main Product Image field in *Product Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Product Description field in *Product Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter product description
   * - **API ID Path**: product_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Product Gallery field in *Product Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.gallery_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_images: prismic.GroupField<
    Simplify<ProductPostDocumentDataGalleryImagesItem>
  >;

  /**
   * Specification Groups field in *Product Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.specification_groups[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  specification_groups: prismic.GroupField<
    Simplify<ProductPostDocumentDataSpecificationGroupsItem>
  >;

  /**
   * Slice Zone field in *Product Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Product Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta title for SEO
   * - **API ID Path**: product_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta description for SEO
   * - **API ID Path**: product_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product Post document from Prismic
 *
 * - **API ID**: `product_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductPostDocumentData>,
    "product_post",
    Lang
  >;

type ProductsPageDocumentDataSlicesSlice = HeroSectionSlice;

/**
 * Content for Products Page documents
 */
interface ProductsPageDocumentData {
  /**
   * title field in *Products Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: products_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Products Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Description ( Must )
   * - **API ID Path**: products_page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Products Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: products_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductsPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Products Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: products_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Products Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: products_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Products Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Products Page document from Prismic
 *
 * - **API ID**: `products_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductsPageDocumentData>,
    "products_page",
    Lang
  >;

/**
 * Item in *Settings → Navigation Links*
 */
export interface SettingsDocumentDataNavItemsItem {
  /**
   * Link Label field in *Settings → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter link text
   * - **API ID Path**: settings.nav_items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link
   * - **API ID Path**: settings.nav_items[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialItemsItem {
  /**
   * Social Platform field in *Settings → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select platform
   * - **API ID Path**: settings.social_items[].platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform: prismic.SelectField<
    | "Instagram"
    | "Facebook"
    | "Twitter"
    | "LinkedIn"
    | "YouTube"
    | "TikTok"
    | "Snapchat"
  >;

  /**
   * Social Link field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter social media URL
   * - **API ID Path**: settings.social_items[].social_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_url: prismic.LinkField;

  /**
   * Icon Name field in *Settings → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select icon
   * - **API ID Path**: settings.social_items[].icon_name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_name: prismic.SelectField<
    | "Instagram"
    | "Facebook"
    | "Twitter"
    | "LinkedIn"
    | "YouTube"
    | "TikTok"
    | "Snapchat"
  >;
}

/**
 * Item in *Settings → Footer Secondary Links*
 */
export interface SettingsDocumentDataFooterSecondaryLinksItem {
  /**
   * Link Label field in *Settings → Footer Secondary Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter link text
   * - **API ID Path**: settings.footer_secondary_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Footer Secondary Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link
   * - **API ID Path**: settings.footer_secondary_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter site title (e.g. Tag Media)
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_items: prismic.GroupField<Simplify<SettingsDocumentDataNavItemsItem>>;

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_items: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialItemsItem>
  >;

  /**
   * Footer Secondary Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_secondary_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_secondary_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSecondaryLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | ClientsDocument
  | ClientsPostDocument
  | HomepageDocument
  | PageDocument
  | ProductPostDocument
  | ProductsPageDocument
  | SettingsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataValuesItem,
      ClientsDocument,
      ClientsDocumentData,
      ClientsDocumentDataSlicesSlice,
      ClientsPostDocument,
      ClientsPostDocumentData,
      ClientsPostDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductPostDocument,
      ProductPostDocumentData,
      ProductPostDocumentDataGalleryImagesItem,
      ProductPostDocumentDataSpecificationGroupsSpecificationsItem,
      ProductPostDocumentDataSpecificationGroupsItem,
      ProductPostDocumentDataSlicesSlice,
      ProductsPageDocument,
      ProductsPageDocumentData,
      ProductsPageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavItemsItem,
      SettingsDocumentDataSocialItemsItem,
      SettingsDocumentDataFooterSecondaryLinksItem,
      AllDocumentTypes,
    };
  }
}
